from __future__ import annotations

import datetime as dt
import logging
import os
from pathlib import Path

from jinja2 import Environment, FileSystemLoader

from amadeus.models.project import ProjectFileModel
from amadeus.models.requirements import RequirementsModel

logger = logging.getLogger(__name__)


class ProjectGenerator:
    """Generates Amadeus handoff workspace files instead of production app code."""

    def __init__(self, **_legacy_kwargs: object) -> None:
        template_dir = Path(__file__).resolve().parents[1] / "docs" / "templates"
        self.jinja_env = Environment(loader=FileSystemLoader(str(template_dir)))

    def generate_all_files(self, requirements: RequirementsModel) -> list[ProjectFileModel]:
        now = dt.datetime.now().strftime("%Y-%m-%d %H:%M")
        files = [
            ProjectFileModel(
                file_path="PROJECT_BRIEF.md",
                content=self._project_brief(requirements, now),
                purpose="Short project orientation",
            ),
            ProjectFileModel(
                file_path="MASTER_PROMPT.md",
                content=self._master_prompt(requirements),
                purpose="Compiled task prompt for the executing agent",
            ),
            ProjectFileModel(
                file_path="REQUIREMENTS.md",
                content=self._requirements(requirements),
                purpose="Structured requirements and non-goals",
            ),
            ProjectFileModel(
                file_path="DECISIONS.md",
                content=self._decisions(requirements),
                purpose="Decisions, assumptions, and rationale",
            ),
            ProjectFileModel(
                file_path="NEXT_STEPS.md",
                content=self._next_steps(requirements),
                purpose="Ordered execution plan",
            ),
            ProjectFileModel(
                file_path="CONTEXT_INDEX.md",
                content=self._context_index(),
                purpose="Context navigation",
            ),
            ProjectFileModel(
                file_path="SOURCE_MAP.md",
                content=self._source_map(),
                purpose="Source provenance map",
            ),
            ProjectFileModel(
                file_path="_logs/raw_input.md",
                content="# Raw Input\n\nRaw voice or text input is recorded here by Amadeus.\n",
                purpose="Raw user input placeholder",
            ),
            ProjectFileModel(
                file_path="_context/README.md",
                content="# Context\n\nConverted source material belongs in this folder.\n",
                purpose="Context folder marker",
            ),
            ProjectFileModel(
                file_path="_sources/README.md",
                content=(
                    "# Sources\n\n"
                    "Original user-provided files belong in this folder unchanged.\n"
                ),
                purpose="Sources folder marker",
            ),
            ProjectFileModel(
                file_path="_skills/README.md",
                content="# Skills\n\nOptional specialist execution instructions belong here.\n",
                purpose="Skills folder marker",
            ),
            ProjectFileModel(
                file_path="_versions/README.md",
                content="# Versions\n\nSnapshots of major workspace changes belong here.\n",
                purpose="Version folder marker",
            ),
        ]

        files.append(
            ProjectFileModel(
                file_path="CLAUDE.md",
                content=self._render_target_template("TARGET_CLAUDE_TEMPLATE.md", requirements),
                purpose="Stateful brain for Claude Code and compatible agents",
            )
        )
        files.append(
            ProjectFileModel(
                file_path="AGENTS.md",
                content=self._render_target_template("TARGET_AGENTS_TEMPLATE.md", requirements),
                purpose="Codex-compatible agent instructions",
            )
        )

        return files

    def _render_target_template(self, template_name: str, requirements: RequirementsModel) -> str:
        constraints = "\n".join(f"- {item}" for item in requirements.quality_criteria)
        commands = "- No project build command is known yet.\n- Follow `NEXT_STEPS.md` first."
        template = self.jinja_env.get_template(template_name)
        rendered = template.render(
            PROJECT_NAME=requirements.display_name,
            PROJECT_GOAL=requirements.short_description,
            CONSTRAINTS=constraints or "- No explicit constraints were captured.",
            COMMANDS=commands,
        )
        return rendered.rstrip() + "\n"

    def _project_brief(self, requirements: RequirementsModel, generated_at: str) -> str:
        return f"""# {requirements.display_name}

Generated by Amadeus: {generated_at}
Workspace type: AI handoff workspace

## Goal

{requirements.short_description}

## Intended Handoff Targets

- Codex
- Claude Code
- Antigravity

## Current State

This workspace contains the prepared context and execution instructions.
The executing agent should not treat Amadeus as having completed the final
project task.
"""

    def _master_prompt(self, requirements: RequirementsModel) -> str:
        specs = self._bullet_list(requirements.specifications)
        quality = self._bullet_list(requirements.quality_criteria)
        return f"""# Master Prompt

## Context

Amadeus prepared this handoff workspace from the user's raw project input.

## Role

You are the executing agent. Complete the task described here using the
workspace files as the source of truth.

## Goal

{requirements.short_description}

## Requirements

{specs}

## Non-Goals

- Do not invent missing source material.
- Do not ignore open questions or documented assumptions.
- Do not delete `_sources/`, `_context/`, `_logs/`, or `_versions/`.

## Working Materials

- Use `_context/` for converted source material.
- Use `_sources/` only when original files are needed.
- Use `SOURCE_MAP.md` before relying on source material.

## Output Expectations

- Complete the user's final task in the target project context.
- Keep decisions traceable in `DECISIONS.md`.
- Preserve the quality criteria below.

## Working Method

- Read `CLAUDE.md` and `AGENTS.md`.
- Follow `NEXT_STEPS.md` in order.
- Ask the user when a blocker cannot be resolved from workspace files.

## Step-by-Step Plan

- Review project brief and requirements.
- Inspect context and source map.
- Resolve blockers or document approved assumptions.
- Execute the task.
- Run verification.
- Summarize outcomes and residual risks.

## Quality Criteria

{quality}

## Risks

- Source material may be incomplete until `_sources/` and `_context/` are populated.
- Open questions must not be hidden.

## Open Questions

- Check `DECISIONS.md` and `NEXT_STEPS.md` for any remaining blocker notes.
"""

    def _requirements(self, requirements: RequirementsModel) -> str:
        return f"""# Requirements

## Project

- Name: {requirements.display_name}
- Folder: `{requirements.project_name}`
- Type: {requirements.project_type}

## Specifications

{self._bullet_list(requirements.specifications)}

## Quality Criteria

{self._bullet_list(requirements.quality_criteria)}

## Planned Handoff Files

{self._file_table(requirements)}
"""

    def _decisions(self, requirements: RequirementsModel) -> str:
        del requirements
        return """# Decisions

## Confirmed Decisions

- Amadeus prepares the handoff workspace; it does not execute the final task.
- Workspace files and folders use English names.
- Original sources are preserved under `_sources/`.
- Converted context belongs under `_context/`.

## Assumptions

- No external source files were available during initial workspace generation unless added later.

## Open Blockers

- Review the generated workspace before execution and add any missing source material.
"""

    def _next_steps(self, requirements: RequirementsModel) -> str:
        del requirements
        return """# Next Steps

1. Read `CLAUDE.md`, `AGENTS.md`, and `MASTER_PROMPT.md`.
2. Check `SOURCE_MAP.md` and `CONTEXT_INDEX.md`.
3. Add or convert missing source materials into `_sources/` and `_context/`.
4. Resolve blockers documented in `DECISIONS.md`.
5. Execute the final user task.
6. Run verification appropriate to the task.
7. Record important scope decisions in `DECISIONS.md`.
"""

    def _context_index(self) -> str:
        return """# Context Index

No converted source files were registered during initial workspace generation.

Add entries in this format:

| Context File | Source ID | Purpose | Notes |
|---|---|---|---|
"""

    def _source_map(self) -> str:
        return """# Source Map

No original sources were registered during initial workspace generation.

Add entries in this format:

| Source ID | Original Source | Converted Context | Purpose | Referenced By |
|---|---|---|---|---|
"""

    def _bullet_list(self, items: list[str]) -> str:
        if not items:
            return "- None captured."
        return "\n".join(f"- {item}" for item in items)

    def _file_table(self, requirements: RequirementsModel) -> str:
        rows = ["| File | Purpose |", "|---|---|"]
        for file in requirements.files_to_create:
            path = os.path.normpath(file.file_path).replace("\\", "/")
            rows.append(f"| `{path}` | {file.purpose} |")
        return "\n".join(rows)
